const colors ={
    colorOne:'#ffff',
    colorTwo:'#96d47f',
    colorThree:'#da67a8',
    colorFour:'#daf1e4',
    backgroundContainerColor1:'#47837b',
    backgroundContainerColor2:'#75cb9c',
    buttonColor1:'#4d876f',
    buttonColor2:'#32858d',
    buttonTextColor:'',
    buttonHoverColor:'',
    buttonHoverTextColor:'',
    typesColor:{
        fire: '#fa3e5d',
        grass: '#DEFDE0',
        electric: '#ffdb24',
        water: '#DEF3FD',
        ground: '#e39b00',
        rock: '#d6b367',
        fairy: '#fceaff',
        poison: '#c76dbe',
        bug: '#6dc76d',
        dragon: '#97b3e6',
        flying: '#67c5d6',
        fighting: '#d66769',
        normal: '#F5F5F5',
        ice:'#3fd0d4',
        psychic:'#49804b',
        steel:'#cfcfcf',
        ghost:'#695282',
        dark: '#200142',
        shadow:'#30385c',
        unknown:'#878787',
    },
    typesBgColor:{
        fire: '#ffff',
        grass: '#000',
        electric: '#000',
        water: '#000',
        ground: '#ffff',
        rock: '#000',
        fairy: '#000',
        poison: '#fff',
        bug: '#ffff',
        dragon: '#ffff',
        flying: '#ffff',
        fighting: '#ffff',
        normal: '#000',
        ice:'#ffff',
        psychic:'#ffff',
        steel:'#000',
        ghost:'#ffff',
        dark: '#ffff',
        shadow:'#ffff',
        unknown:'#ffff',
    },
}

export default  colors